version: "3"
# A Docker Compose file for configuration of the development environment

services:
  # load balancer
  lb:
    build: simplestlb
    image: hopla/simplest-lab:simplestlb
    environment:
      - APPLICATION_ALIAS=simplestapp
      - APPLICATION_PORT=3000
    networks:
      simplestlab:
          aliases:
          - simplestlb
    ports:
      - "8080:80"

  db:
    build: simplestdb
    image: hopla/simplest-lab:simplestdb
    environment:
        - "POSTGRES_PASSWORD=changeme"
    networks:
       simplestlab:
        aliases:
          - simplestdb

  app:
    build: simplestapp
    image: hopla/simplest-lab:simplestapp
    environment:
      - dbhost=simplestdb
      - dbname=demo
      - dbuser=demo
      - dbpasswd=d3m0
    networks:
       simplestlab:
        aliases:
          - simplestapp
    depends_on:
      - lb
      - db
    deploy:
      #mode: global
      #replicas: 10

networks:
  simplestlab:
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.0.0/16

